CREATE TABLE  "PROGRAMAS" 
   (	"PROGRAMA" VARCHAR2(5), 
	"NOMBRE_PROGRAMA" VARCHAR2(100) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(2000), 
	 CONSTRAINT "PROGRAMAS_PK" PRIMARY KEY ("PROGRAMA")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "SERVICIOS" 
   (	"SECCION_FK" NUMBER(4,0), 
	"SERVICIO" NUMBER(4,0), 
	"NOMBRE_SERVICIO" VARCHAR2(100), 
	 CONSTRAINT "SERVICIOS_PK" PRIMARY KEY ("SECCION_FK", "SERVICIO")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "PROYECTOS_INVERSION" 
   (	"PROYECTO_INVERSION" VARCHAR2(15), 
	"DESCRIPCION" VARCHAR2(100) NOT NULL ENABLE, 
	"SECCION_FK" NUMBER(4,0) NOT NULL ENABLE, 
	"SERVICIO_FK" NUMBER(4,0) NOT NULL ENABLE, 
	"PROGRAMA_FK" VARCHAR2(5) NOT NULL ENABLE, 
	 CONSTRAINT "PROYECTOS_INVERSION_PK" PRIMARY KEY ("PROYECTO_INVERSION")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "TIPOS_MODIFICACIONES_PRESUPUESTARIAS" 
   (	"TIPO_MODIFICACION_PRESUP" VARCHAR2(20), 
	"DESCRIPCION" VARCHAR2(200), 
	 CONSTRAINT "TIPOS_MODIFICACIONES_PRESUPUESTARIAS_PK" PRIMARY KEY ("TIPO_MODIFICACION_PRESUP")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "MODIFICACIONES_PRESUPUESTO" 
   (	"ID_MODIFICACION" NUMBER(4,0), 
	"SECCION" VARCHAR2(4), 
	"SERVICIO" VARCHAR2(4), 
	"PROGRAMA" VARCHAR2(5), 
	"CONCEPTO" VARCHAR2(10), 
	"ANO" NUMBER(4,0), 
	"ACTIVO" CHAR(1), 
	"TIPO_MODIFICACION_PRESUPUESTO" VARCHAR2(20), 
	"FECHA_ENVIO" TIMESTAMP (6), 
	"OF_PRESUPUESTARIA" CHAR(1), 
	"IMPORTE" NUMBER(2,8), 
	"DESCRIPCION" VARCHAR2(100), 
	"PROYECTO_INVERSION" VARCHAR2(20), 
	"COMENTARIOS" VARCHAR2(1000), 
	 CONSTRAINT "MODIFICACIONES_PRESUPUESTO_PK" PRIMARY KEY ("ID_MODIFICACION")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "TIPOS_EVENTO_CONTRATACION" 
   (	"TIPO_EVENTO" VARCHAR2(20), 
	"DESCRIPCION" VARCHAR2(100), 
	 CONSTRAINT "TIPOS_EVENTO_CONTRATACION_PK" PRIMARY KEY ("TIPO_EVENTO")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "PROCEDIMIENTOS_CONTRATACION" 
   (	"PROC_CONTRATACION" VARCHAR2(100), 
	"DESCRIPCION" VARCHAR2(400), 
	 CONSTRAINT "PROCEDIMIENTOS_CONTRATACION_PK" PRIMARY KEY ("PROC_CONTRATACION")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "EVENTOS_PROCEDIMIENTOS_CONTRATACION" 
   (	"TIPO_EVENTO_FK" VARCHAR2(20), 
	"PROC_CONTRATACION_FK" VARCHAR2(100), 
	 CONSTRAINT "EVENTOS_PROCEDIMIENTOS_CONTRATACION_PK" PRIMARY KEY ("TIPO_EVENTO_FK", "PROC_CONTRATACION_FK")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "ORGANISMOS" 
   (	"ID_ORGANISMO" NUMBER NOT NULL ENABLE, 
	"NIF" VARCHAR2(15), 
	"NOMBRE_ORGANISMO" VARCHAR2(100), 
	"CONTACTO" VARCHAR2(200), 
	"EMAIL" VARCHAR2(30), 
	"TELEFONO1" VARCHAR2(15), 
	"TELEFONO2" VARCHAR2(15), 
	"DIRECCION" VARCHAR2(200), 
	"CP" VARCHAR2(10), 
	"POBLACION" VARCHAR2(50), 
	"PROVINCIA" VARCHAR2(20), 
	"FAX" VARCHAR2(15), 
	"COMENTARIOS" VARCHAR2(4000), 
	 CONSTRAINT "ORGANISMOS_PK" PRIMARY KEY ("ID_ORGANISMO")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "SISTEMAS" 
   (	"SISTEMA" VARCHAR2(20), 
	"DESCRIPCION" VARCHAR2(200), 
	 CONSTRAINT "SISTEMAS_PK" PRIMARY KEY ("SISTEMA")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "GENERADORES_PAGO" 
   (	"ID_GENERADOR_PAGO" NUMBER(4,0), 
	"SISTEMA" VARCHAR2(20), 
	"ORGANISMO_RECEPTOR" NUMBER(4,0), 
	"FECHA_FIRMA" TIMESTAMP (6), 
	"FECHA_INICIO" TIMESTAMP (6), 
	"FECHA_FIN" TIMESTAMP (6), 
	"FECHA_FIN_PRORROGA" TIMESTAMP (6), 
	"CONDICIONES_PRORROGA" NVARCHAR2(200), 
	"TIPO_LEGAL" VARCHAR2(20), 
	"EMAIL_ESPECIFICO" VARCHAR2(50), 
	"COMENTARIOS" VARCHAR2(1000), 
	"DOCUMENTACION" BLOB, 
	 CONSTRAINT "GENERADORES_PAGO_PK" PRIMARY KEY ("ID_GENERADOR_PAGO")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "TIPOS_LEGAL" 
   (	"TIPO_LEGAL" VARCHAR2(20), 
	"DESCRIPCION" VARCHAR2(200), 
	 CONSTRAINT "TIPOS_LEGAL_PK" PRIMARY KEY ("TIPO_LEGAL")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "GENERADORES_INGRESO" 
   (	"ID_GENERADOR_INGRESO" NUMBER(4,0), 
	"SISTEMA" VARCHAR2(20), 
	"ORGANISMO" NUMBER(4,0), 
	"FECHA_FIRMA" TIMESTAMP (6), 
	"FECHA_INICIO" TIMESTAMP (6), 
	"FECHA_FIN" TIMESTAMP (6), 
	"FECHA_FIN_PRORROGA" TIMESTAMP (6), 
	"CONDICIONES_PRORROGA" VARCHAR2(1000), 
	"TIPO_LEGAL" VARCHAR2(20), 
	"EMAIL_ESPECIFICO" VARCHAR2(100), 
	"COMENTARIOS" VARCHAR2(1000), 
	"DOCUMENTO" BLOB, 
	 CONSTRAINT "GENERADORES_INGRESO_PK" PRIMARY KEY ("ID_GENERADOR_INGRESO")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "RESERVAS_CAJAFIJA" 
   (	"SECCION" VARCHAR2(4), 
	"SERVICIO" VARCHAR2(4), 
	"PROGRAMA" VARCHAR2(5), 
	"CONCEPTO" VARCHAR2(10), 
	"ANO" NUMBER(4,0), 
	"VINCULANTE" VARCHAR2(5), 
	"IMPORTE" NUMBER(2,8), 
	"UDSGAF" VARCHAR2(15), 
	 CONSTRAINT "RESERVAS_CAJAFIJA_PK" PRIMARY KEY ("SECCION", "SERVICIO", "PROGRAMA", "CONCEPTO", "ANO")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "CAJAS_FIJA" 
   (	"CAJA_FIJA" NUMBER(5,0), 
	"SECCION" VARCHAR2(4), 
	"SERVICIO" VARCHAR2(4), 
	"PROGRAMA" VARCHAR2(5), 
	"CONCEPTO" VARCHAR2(10), 
	"ANO" NUMBER(4,0), 
	"DESCRIPCION" VARCHAR2(100), 
	"COMENTARIOS" VARCHAR2(1000), 
	 CONSTRAINT "CAJAS_FIJA_PK" PRIMARY KEY ("CAJA_FIJA")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "DOCUMENTOS_CAJA_FIJA" 
   (	"CAJA_FIJA" NUMBER(5,0), 
	"NOMBRE" VARCHAR2(50), 
	"TIPO_DOCUMENTO" VARCHAR2(20), 
	"FICHERO" BLOB NOT NULL ENABLE, 
	"COMENTARIOS" VARCHAR2(200), 
	 CONSTRAINT "DOCUMENTOS_CAJA_FIJA_PK" PRIMARY KEY ("CAJA_FIJA", "NOMBRE")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "TIPOS_MODELO" 
   (	"TIPO_MODELO" VARCHAR2(25), 
	"NOMBRE" VARCHAR2(50), 
	"DESCRIPCION" VARCHAR2(100), 
	 CONSTRAINT "TIPOS_MODELO_PK" PRIMARY KEY ("TIPO_MODELO")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "MODELO" 
   (	"ID_MODELO" NUMBER(4,0), 
	"NOMBRE" VARCHAR2(50), 
	"TIPO_MODELO" VARCHAR2(20), 
	"DESCRIPCION" VARCHAR2(1000), 
	 CONSTRAINT "MODELO_PK" PRIMARY KEY ("ID_MODELO")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "DOCUMENTOS_MODELO" 
   (	"ID_MODELO" NUMBER(4,0), 
	"NUM_VERSION" NUMBER(3,0), 
	"DOCUMENTACION" BLOB, 
	"COMENTARIOS" VARCHAR2(1000), 
	 CONSTRAINT "DOCUMENTOS_MODELO_PK" PRIMARY KEY ("ID_MODELO", "NUM_VERSION")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "PAGOS" 
   (	"ID_PAGO" NUMBER(4,0), 
	"IMPORTE" NUMBER(2,8), 
	"FECHA_INICIO_LIQUIDACION" TIMESTAMP (6), 
	"FECHA_FIN_LIQUIDACION" TIMESTAMP (6), 
	"DESCRIPCION" VARCHAR2(200), 
	"ID_MODIFICACION" NUMBER(4,0), 
	"ID_GENERADOR_PAG" NUMBER(4,0), 
	"COMENTARIOS" VARCHAR2(1000), 
	 CONSTRAINT "PAGOS_PK" PRIMARY KEY ("ID_PAGO")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "DOCUMENTOS_MODIFICACIONES" 
   (	"ID_MODIFICACION" NUMBER(4,0), 
	"NUM_DOCUMENTO" NUMBER(4,0), 
	"TIPO_DOC_ENVIO" VARCHAR2(20), 
	"DOCUMENTACION" BLOB, 
	"COMENTARIOS" VARCHAR2(1000), 
	 CONSTRAINT "DOCUMENTOS_MODIFICACIONES_PK" PRIMARY KEY ("ID_MODIFICACION", "NUM_DOCUMENTO")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "INGRESOS" 
   (	"ID_INGRESO" NUMBER(4,0), 
	"IMPORTE" NUMBER(2,4), 
	"FECHA_INICIO_LIQUIDACION" TIMESTAMP (6), 
	"FECHA_FIN_LIQUIDACION" TIMESTAMP (6), 
	"DESCRIPCION" VARCHAR2(100), 
	"DOCUMENTO" BLOB, 
	"FECHA_ENVIO" TIMESTAMP (6), 
	"NUM_JUSTIFICANTE" VARCHAR2(15), 
	"TIPO" VARCHAR2(15), 
	"ESTADO" VARCHAR2(15), 
	"NUM_TESORO" VARCHAR2(15), 
	"ID_MODIFICACION" NUMBER(4,0), 
	"ID_GENERADOR_INGRESOS" NUMBER(4,0), 
	"COMENTARIOS" VARCHAR2(1000), 
	 CONSTRAINT "INGRESOS_PK" PRIMARY KEY ("ID_INGRESO")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "VINCULANTES" 
   (	"VINCULANTE" NUMBER(5,0), 
	"DESCRIPCION" VARCHAR2(100), 
	 CONSTRAINT "VINCULANTES_PK" PRIMARY KEY ("VINCULANTE")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "UNIDADES_SFAF" 
   (	"UDSGAF" VARCHAR2(15), 
	"DESCRIPCION" VARCHAR2(200), 
	 CONSTRAINT "UNIDADES_SFAF_PK" PRIMARY KEY ("UDSGAF")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "TIPOS_TRAMITACION" 
   (	"TIPO_TRAMITACION" VARCHAR2(20), 
	"DESCRIPCION" VARCHAR2(200)
   )
/
CREATE TABLE  "PAGADORES" 
   (	"ID_PAGADOR" VARCHAR2(20), 
	"DESCRIPCION" VARCHAR2(200), 
	"DATOS_PAGADOR" VARCHAR2(200), 
	 CONSTRAINT "PAGADORES_PK" PRIMARY KEY ("ID_PAGADOR")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "TIPOS_DOCUMENTO_CONTRATACION" 
   (	"TIPO_DOCUMENTO_CONTRATACION" VARCHAR2(30), 
	"DESCRIPCION" VARCHAR2(200), 
	 CONSTRAINT "TIPOS_DOCUMENTO_CONTRATACION_PK" PRIMARY KEY ("TIPO_DOCUMENTO_CONTRATACION")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "FUNCIONES" 
   (	"ALIAS_FUNCION" VARCHAR2(15), 
	"NOMBRE_FUNCION" VARCHAR2(50) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(1000), 
	 CONSTRAINT "FUNCIONES_PK" PRIMARY KEY ("ALIAS_FUNCION")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "PRIORIDADES" 
   (	"PRIORIDAD" NUMBER(2,0), 
	"DESCRIPCION" VARCHAR2(100), 
	 CONSTRAINT "PRIORIDADES_PK" PRIMARY KEY ("PRIORIDAD")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "UNIDADES_PROPONENTES" 
   (	"ALIAS_UNIDAD" VARCHAR2(10) NOT NULL ENABLE, 
	"NOMBRE_UNIDAD" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "UNIDADES_PROPONENTES_PK" PRIMARY KEY ("ALIAS_UNIDAD")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "EJERCICIOS_FUTUROS" 
   (	"TIPO_EJERCICIOS_FUTUROS" VARCHAR2(3), 
	"DESCRIPCION" VARCHAR2(30), 
	 CONSTRAINT "EJERCICIOS_FUTUROS_PK" PRIMARY KEY ("TIPO_EJERCICIOS_FUTUROS")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "SECCIONES" 
   (	"SECCION" NUMBER(4,0), 
	"NOMBRE_SECCION" VARCHAR2(200), 
	 CONSTRAINT "SECCIONES_PK" PRIMARY KEY ("SECCION")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "PROVEEDORES" 
   (	"ID_PROVEEDOR" NUMBER NOT NULL ENABLE, 
	"NIF" VARCHAR2(15), 
	"NOMBRE_PROVEEDOR" VARCHAR2(100), 
	"CONTACTO" VARCHAR2(200), 
	"EMAIL" VARCHAR2(30), 
	"TELEFONO1" VARCHAR2(15), 
	"TELEFONO2" VARCHAR2(15), 
	"DIRECCION" VARCHAR2(200), 
	"CP" VARCHAR2(10), 
	"POBLACION" VARCHAR2(50), 
	"PROVINCIA" VARCHAR2(20), 
	"FAX" VARCHAR2(15), 
	"COMENTARIOS" VARCHAR2(4000), 
	 CONSTRAINT "PROVEEDORES_PK" PRIMARY KEY ("ID_PROVEEDOR")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "TIPOS_EVENTO_FACTURACION" 
   (	"TIPO_EVENTO" VARCHAR2(20), 
	"DESCRIPCION" VARCHAR2(200), 
	 CONSTRAINT "TIPOS_EVENTO_FACTURACION_PK" PRIMARY KEY ("TIPO_EVENTO")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "DESTINATARIOS" 
   (	"DESTINATARIO" VARCHAR2(15), 
	"NOMBRE" VARCHAR2(200), 
	 CONSTRAINT "DESTINATARIOS_PK" PRIMARY KEY ("DESTINATARIO")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "TIPOS_CONTRATACION" 
   (	"TIPO_CONTRATACION" VARCHAR2(25), 
	"DESCRIPCION" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "TIPOS_CONTRATACION_PK" PRIMARY KEY ("TIPO_CONTRATACION")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "INDS_IGAE" 
   (	"ALIAS_INDICADOR" VARCHAR2(15), 
	"DESCRIPCION" VARCHAR2(200), 
	 CONSTRAINT "INDS_IGAE_PK" PRIMARY KEY ("ALIAS_INDICADOR")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "ESTADOS_PREVISION" 
   (	"ESTADO_PREVISION" VARCHAR2(10), 
	"DESCRIPCION" VARCHAR2(100), 
	 CONSTRAINT "ESTADOS_PREVISION_PK" PRIMARY KEY ("ESTADO_PREVISION")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "CONCEPTOS" 
   (	"CONCEPTO" NUMBER(10,0), 
	"VINCULANTE_FK" NUMBER(5,0) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "CONCEPTOS_PK" PRIMARY KEY ("CONCEPTO")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "JEFES_DE_PROYECTO" 
   (	"ID_JP" VARCHAR2(6) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(50) NOT NULL ENABLE, 
	"APELLIDO1" VARCHAR2(50) NOT NULL ENABLE, 
	"APELLIDO2" VARCHAR2(50) NOT NULL ENABLE, 
	"COMENTARIOS" VARCHAR2(4000), 
	 CONSTRAINT "JEFES_DE_PROYECTO_PK" PRIMARY KEY ("ID_JP")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "TIPOS_EVENTO_PLANIFICACION" 
   (	"TIPO_EVENTO" VARCHAR2(20), 
	"DESCRIPCION" VARCHAR2(200), 
	 CONSTRAINT "TIPOS_EVENTO_PLANIFICACION_PK" PRIMARY KEY ("TIPO_EVENTO")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "TIPOS_DOCUMENTO_FACTURACION" 
   (	"TIPO_DOCUMENTO_FACTURACION" VARCHAR2(15), 
	"DESCRIPCION" VARCHAR2(200) NOT NULL ENABLE
   )
/
CREATE TABLE  "ORGANOS_CONTRATACION" 
   (	"ALIAS_ORGANO_CONTRATACION" VARCHAR2(6), 
	"NOMBRE" VARCHAR2(100), 
	 CONSTRAINT "ORGANOS_CONTRATACION_PK" PRIMARY KEY ("ALIAS_ORGANO_CONTRATACION")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "TRAMITADORES" 
   (	"ID_TRAMITADOR" VARCHAR2(6), 
	"NOMBRE" VARCHAR2(50) NOT NULL ENABLE, 
	"APELLIDO1" VARCHAR2(50) NOT NULL ENABLE, 
	"APELLIDO2" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "TRAMITADORES_PK" PRIMARY KEY ("ID_TRAMITADOR")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "TIPOS_ATRIBUTO_PREVISION" 
   (	"TIPO_ATRIBUTO_PREVISION" VARCHAR2(20), 
	"DESCRIPCION" VARCHAR2(100) NOT NULL ENABLE, 
	"ACTIVO" CHAR(1), 
	 CONSTRAINT "TIPOS_ATRIBUTO_PREVISION_PK" PRIMARY KEY ("TIPO_ATRIBUTO_PREVISION")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "PROYECTOS_INVERSION" ADD CONSTRAINT "PROYECTOS_INVERSION_SERVICIO_FK" FOREIGN KEY ("SECCION_FK", "SERVICIO_FK")
	  REFERENCES  "SERVICIOS" ("SECCION_FK", "SERVICIO") ENABLE
/
ALTER TABLE  "PROYECTOS_INVERSION" ADD CONSTRAINT "PROYECTOS_INVERSION_PROGRAMA" FOREIGN KEY ("PROGRAMA_FK")
	  REFERENCES  "PROGRAMAS" ("PROGRAMA") ENABLE
/
ALTER TABLE  "EVENTOS_PROCEDIMIENTOS_CONTRATACION" ADD CONSTRAINT "EVENTOS_PROCEDIMIENTOS_CONTRATACION_TIPO_EVENTO_FK" FOREIGN KEY ("TIPO_EVENTO_FK")
	  REFERENCES  "TIPOS_EVENTO_CONTRATACION" ("TIPO_EVENTO") ENABLE
/
ALTER TABLE  "EVENTOS_PROCEDIMIENTOS_CONTRATACION" ADD CONSTRAINT "EVENTOS_PROCEDIMIENTOS_CONTRATACION_PROC_CONTRATACION_FK" FOREIGN KEY ("PROC_CONTRATACION_FK")
	  REFERENCES  "PROCEDIMIENTOS_CONTRATACION" ("PROC_CONTRATACION") ENABLE
/
ALTER TABLE  "CAJAS_FIJA" ADD CONSTRAINT "CAJAS_FIJA_FK" FOREIGN KEY ("SECCION", "SERVICIO", "PROGRAMA", "CONCEPTO", "ANO")
	  REFERENCES  "RESERVAS_CAJAFIJA" ("SECCION", "SERVICIO", "PROGRAMA", "CONCEPTO", "ANO") ENABLE
/
ALTER TABLE  "DOCUMENTOS_CAJA_FIJA" ADD CONSTRAINT "DOCUMENTOS_CAJA_FIJA_FK" FOREIGN KEY ("CAJA_FIJA")
	  REFERENCES  "CAJAS_FIJA" ("CAJA_FIJA") ENABLE
/
ALTER TABLE  "MODELO" ADD CONSTRAINT "MODELO_FK" FOREIGN KEY ("TIPO_MODELO")
	  REFERENCES  "TIPOS_MODELO" ("TIPO_MODELO") ENABLE
/
ALTER TABLE  "DOCUMENTOS_MODELO" ADD CONSTRAINT "DOCUMENTOS_MODELO_FK" FOREIGN KEY ("ID_MODELO")
	  REFERENCES  "MODELO" ("ID_MODELO") ENABLE
/
ALTER TABLE  "GENERADORES_PAGO" ADD CONSTRAINT "GENERADORES_PAGO_SISTEMA_FK" FOREIGN KEY ("SISTEMA")
	  REFERENCES  "SISTEMAS" ("SISTEMA") ENABLE
/
ALTER TABLE  "GENERADORES_PAGO" ADD CONSTRAINT "GENERADORES_PAGO_ORG_FK" FOREIGN KEY ("ORGANISMO_RECEPTOR")
	  REFERENCES  "ORGANISMOS" ("ID_ORGANISMO") ENABLE
/
ALTER TABLE  "MODIFICACIONES_PRESUPUESTO" ADD CONSTRAINT "MODIFICACIONES_PRESUPUESTO_PROGRAMA_FK" FOREIGN KEY ("PROGRAMA")
	  REFERENCES  "PROGRAMAS" ("PROGRAMA") ENABLE
/
ALTER TABLE  "MODIFICACIONES_PRESUPUESTO" ADD CONSTRAINT "MODIFICACIONES_PRESUPUESTO_TIPO_FK" FOREIGN KEY ("TIPO_MODIFICACION_PRESUPUESTO")
	  REFERENCES  "TIPOS_MODIFICACIONES_PRESUPUESTARIAS" ("TIPO_MODIFICACION_PRESUP") ENABLE
/
ALTER TABLE  "DOCUMENTOS_MODIFICACIONES" ADD CONSTRAINT "DOCUMENTOS_MODIFICACIONES_FK" FOREIGN KEY ("ID_MODIFICACION")
	  REFERENCES  "MODIFICACIONES_PRESUPUESTO" ("ID_MODIFICACION") ENABLE
/
ALTER TABLE  "GENERADORES_INGRESO" ADD CONSTRAINT "GENERADORES_INGRESO_SISTEMA_FK" FOREIGN KEY ("SISTEMA")
	  REFERENCES  "SISTEMAS" ("SISTEMA") ENABLE
/
ALTER TABLE  "GENERADORES_INGRESO" ADD CONSTRAINT "GENERADORES_INGRESO_ORGANISMO_FK" FOREIGN KEY ("ORGANISMO")
	  REFERENCES  "ORGANISMOS" ("ID_ORGANISMO") ENABLE
/
ALTER TABLE  "GENERADORES_INGRESO" ADD CONSTRAINT "GENERADORES_INGRESO_TIPO_FK" FOREIGN KEY ("TIPO_LEGAL")
	  REFERENCES  "TIPOS_LEGAL" ("TIPO_LEGAL") ENABLE
/
ALTER TABLE  "PAGOS" ADD CONSTRAINT "PAGOS_MODIFICACION_FK" FOREIGN KEY ("ID_MODIFICACION")
	  REFERENCES  "MODIFICACIONES_PRESUPUESTO" ("ID_MODIFICACION") ENABLE
/
ALTER TABLE  "PAGOS" ADD CONSTRAINT "PAGOS_GENERADORES_FK" FOREIGN KEY ("ID_GENERADOR_PAG")
	  REFERENCES  "GENERADORES_PAGO" ("ID_GENERADOR_PAGO") ENABLE
/
ALTER TABLE  "INGRESOS" ADD CONSTRAINT "INGRESOS_MODIFICACION_FK" FOREIGN KEY ("ID_MODIFICACION")
	  REFERENCES  "MODIFICACIONES_PRESUPUESTO" ("ID_MODIFICACION") ENABLE
/
ALTER TABLE  "INGRESOS" ADD CONSTRAINT "INGRESOS_GENERADOR_FK" FOREIGN KEY ("ID_GENERADOR_INGRESOS")
	  REFERENCES  "GENERADORES_INGRESO" ("ID_GENERADOR_INGRESO") ENABLE
/
CREATE UNIQUE INDEX  "CAJAS_FIJA_PK" ON  "CAJAS_FIJA" ("CAJA_FIJA")
/
CREATE UNIQUE INDEX  "CONCEPTOS_PK" ON  "CONCEPTOS" ("CONCEPTO")
/
CREATE UNIQUE INDEX  "DESTINATARIOS_PK" ON  "DESTINATARIOS" ("DESTINATARIO")
/
CREATE UNIQUE INDEX  "DOCUMENTOS_CAJA_FIJA_PK" ON  "DOCUMENTOS_CAJA_FIJA" ("CAJA_FIJA", "NOMBRE")
/
CREATE UNIQUE INDEX  "DOCUMENTOS_MODELO_PK" ON  "DOCUMENTOS_MODELO" ("ID_MODELO", "NUM_VERSION")
/
CREATE UNIQUE INDEX  "DOCUMENTOS_MODIFICACIONES_PK" ON  "DOCUMENTOS_MODIFICACIONES" ("ID_MODIFICACION", "NUM_DOCUMENTO")
/
CREATE UNIQUE INDEX  "EJERCICIOS_FUTUROS_PK" ON  "EJERCICIOS_FUTUROS" ("TIPO_EJERCICIOS_FUTUROS")
/
CREATE UNIQUE INDEX  "ESTADOS_PREVISION_PK" ON  "ESTADOS_PREVISION" ("ESTADO_PREVISION")
/
CREATE UNIQUE INDEX  "EVENTOS_PROCEDIMIENTOS_CONTRATACION_PK" ON  "EVENTOS_PROCEDIMIENTOS_CONTRATACION" ("TIPO_EVENTO_FK", "PROC_CONTRATACION_FK")
/
CREATE UNIQUE INDEX  "FUNCIONES_PK" ON  "FUNCIONES" ("ALIAS_FUNCION")
/
CREATE UNIQUE INDEX  "GENERADORES_INGRESO_PK" ON  "GENERADORES_INGRESO" ("ID_GENERADOR_INGRESO")
/
CREATE UNIQUE INDEX  "GENERADORES_PAGO_PK" ON  "GENERADORES_PAGO" ("ID_GENERADOR_PAGO")
/
CREATE UNIQUE INDEX  "INDS_IGAE_PK" ON  "INDS_IGAE" ("ALIAS_INDICADOR")
/
CREATE UNIQUE INDEX  "INGRESOS_PK" ON  "INGRESOS" ("ID_INGRESO")
/
CREATE UNIQUE INDEX  "JEFES_DE_PROYECTO_PK" ON  "JEFES_DE_PROYECTO" ("ID_JP")
/
CREATE UNIQUE INDEX  "MODELO_PK" ON  "MODELO" ("ID_MODELO")
/
CREATE UNIQUE INDEX  "MODIFICACIONES_PRESUPUESTO_PK" ON  "MODIFICACIONES_PRESUPUESTO" ("ID_MODIFICACION")
/
CREATE UNIQUE INDEX  "ORGANISMOS_PK" ON  "ORGANISMOS" ("ID_ORGANISMO")
/
CREATE UNIQUE INDEX  "ORGANOS_CONTRATACION_PK" ON  "ORGANOS_CONTRATACION" ("ALIAS_ORGANO_CONTRATACION")
/
CREATE UNIQUE INDEX  "PAGADORES_PK" ON  "PAGADORES" ("ID_PAGADOR")
/
CREATE UNIQUE INDEX  "PAGOS_PK" ON  "PAGOS" ("ID_PAGO")
/
CREATE UNIQUE INDEX  "PRIORIDADES_PK" ON  "PRIORIDADES" ("PRIORIDAD")
/
CREATE UNIQUE INDEX  "PROCEDIMIENTOS_CONTRATACION_PK" ON  "PROCEDIMIENTOS_CONTRATACION" ("PROC_CONTRATACION")
/
CREATE UNIQUE INDEX  "PROGRAMAS_PK" ON  "PROGRAMAS" ("PROGRAMA")
/
CREATE UNIQUE INDEX  "PROVEEDORES_PK" ON  "PROVEEDORES" ("ID_PROVEEDOR")
/
CREATE UNIQUE INDEX  "PROYECTOS_INVERSION_PK" ON  "PROYECTOS_INVERSION" ("PROYECTO_INVERSION")
/
CREATE UNIQUE INDEX  "RESERVAS_CAJAFIJA_PK" ON  "RESERVAS_CAJAFIJA" ("SECCION", "SERVICIO", "PROGRAMA", "CONCEPTO", "ANO")
/
CREATE UNIQUE INDEX  "SECCIONES_PK" ON  "SECCIONES" ("SECCION")
/
CREATE UNIQUE INDEX  "SERVICIOS_PK" ON  "SERVICIOS" ("SECCION_FK", "SERVICIO")
/
CREATE UNIQUE INDEX  "SISTEMAS_PK" ON  "SISTEMAS" ("SISTEMA")
/
CREATE UNIQUE INDEX  "TIPOS_ATRIBUTO_PREVISION_PK" ON  "TIPOS_ATRIBUTO_PREVISION" ("TIPO_ATRIBUTO_PREVISION")
/
CREATE UNIQUE INDEX  "TIPOS_CONTRATACION_PK" ON  "TIPOS_CONTRATACION" ("TIPO_CONTRATACION")
/
CREATE UNIQUE INDEX  "TIPOS_DOCUMENTO_CONTRATACION_PK" ON  "TIPOS_DOCUMENTO_CONTRATACION" ("TIPO_DOCUMENTO_CONTRATACION")
/
CREATE UNIQUE INDEX  "TIPOS_EVENTO_CONTRATACION_PK" ON  "TIPOS_EVENTO_CONTRATACION" ("TIPO_EVENTO")
/
CREATE UNIQUE INDEX  "TIPOS_EVENTO_FACTURACION_PK" ON  "TIPOS_EVENTO_FACTURACION" ("TIPO_EVENTO")
/
CREATE UNIQUE INDEX  "TIPOS_EVENTO_PLANIFICACION_PK" ON  "TIPOS_EVENTO_PLANIFICACION" ("TIPO_EVENTO")
/
CREATE UNIQUE INDEX  "TIPOS_LEGAL_PK" ON  "TIPOS_LEGAL" ("TIPO_LEGAL")
/
CREATE UNIQUE INDEX  "TIPOS_MODELO_PK" ON  "TIPOS_MODELO" ("TIPO_MODELO")
/
CREATE UNIQUE INDEX  "TIPOS_MODIFICACIONES_PRESUPUESTARIAS_PK" ON  "TIPOS_MODIFICACIONES_PRESUPUESTARIAS" ("TIPO_MODIFICACION_PRESUP")
/
CREATE UNIQUE INDEX  "TRAMITADORES_PK" ON  "TRAMITADORES" ("ID_TRAMITADOR")
/
CREATE UNIQUE INDEX  "UNIDADES_PROPONENTES_PK" ON  "UNIDADES_PROPONENTES" ("ALIAS_UNIDAD")
/
CREATE UNIQUE INDEX  "UNIDADES_SFAF_PK" ON  "UNIDADES_SFAF" ("UDSGAF")
/
CREATE UNIQUE INDEX  "VINCULANTES_PK" ON  "VINCULANTES" ("VINCULANTE")
/
 CREATE SEQUENCE   "PRUEBA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/
 CREATE SEQUENCE   "PROVEEDORES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/
 CREATE SEQUENCE   "CAJAS_FIJA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/
 CREATE SEQUENCE   "MODELO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/
 CREATE SEQUENCE   "GENERADORES_PAGO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/
 CREATE SEQUENCE   "MODIFICACIONES_PRESUPUESTO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/
 CREATE SEQUENCE   "GENERADORES_INGRESO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/
 CREATE SEQUENCE   "PAGOS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/
 CREATE SEQUENCE   "INGRESOS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_CAJAS_FIJA" 
  before insert on "CAJAS_FIJA"               
  for each row  
begin   
  if :NEW."CAJA_FIJA" is null then 
    select "CAJAS_FIJA_SEQ".nextval into :NEW."CAJA_FIJA" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_CAJAS_FIJA" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_GENERADORES_INGRESO" 
  before insert on "GENERADORES_INGRESO"               
  for each row  
begin   
  if :NEW."ID_GENERADOR_INGRESO" is null then 
    select "GENERADORES_INGRESO_SEQ".nextval into :NEW."ID_GENERADOR_INGRESO" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_GENERADORES_INGRESO" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_GENERADORES_PAGO" 
  before insert on "GENERADORES_PAGO"               
  for each row  
begin   
  if :NEW."ID_GENERADOR_PAGO" is null then 
    select "GENERADORES_PAGO_SEQ".nextval into :NEW."ID_GENERADOR_PAGO" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_GENERADORES_PAGO" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_INGRESOS" 
  before insert on "INGRESOS"               
  for each row  
begin   
  if :NEW."ID_INGRESO" is null then 
    select "INGRESOS_SEQ".nextval into :NEW."ID_INGRESO" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_INGRESOS" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_MODELO" 
  before insert on "MODELO"               
  for each row  
begin   
  if :NEW."ID_MODELO" is null then 
    select "MODELO_SEQ".nextval into :NEW."ID_MODELO" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_MODELO" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_MODIFICACIONES_PRESUPUESTO" 
  before insert on "MODIFICACIONES_PRESUPUESTO"               
  for each row  
begin   
  if :NEW."ID_MODIFICACION" is null then 
    select "MODIFICACIONES_PRESUPUESTO_SEQ".nextval into :NEW."ID_MODIFICACION" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_MODIFICACIONES_PRESUPUESTO" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_PAGOS" 
  before insert on "PAGOS"               
  for each row  
begin   
  if :NEW."ID_PAGO" is null then 
    select "PAGOS_SEQ".nextval into :NEW."ID_PAGO" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_PAGOS" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_PROVEEDORES" 
  before insert on "PROVEEDORES"               
  for each row  
begin   
  if :NEW."ID_PROVEEDOR" is null then 
    select "PROVEEDORES_SEQ".nextval into :NEW."ID_PROVEEDOR" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_PROVEEDORES" ENABLE
/
